# Generated by Django 6.0.3 on 2026-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to="profile_pics/"),
        ),
    ]
