# Generated by Django 6.0.3 on 2026-04-12 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_is_seller_alter_seller_is_approved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellerapplication",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="sellerapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
