# Generated by Django 6.0.3 on 2026-03-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
