# Generated by Django 6.0.3 on 2026-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_order_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
