# Generated by Django 6.0.3 on 2026-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_productimage_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banners/")),
                ("title", models.CharField(blank=True, max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
