# Generated by Django 6.0.3 on 2026-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_order_status_order_tracking_id_order_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount", models.IntegerField()),
                ("min_amount", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
