# Generated by Django 6.0.3 on 2026-03-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="landmark",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cod", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
