# Generated by Django 6.0.3 on 2026-04-02 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_seller"),
        ("products", "0011_order_is_paid_order_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.seller",
            ),
        ),
    ]
